# Generated by Django 5.0.7 on 2024-07-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_car_photo_car_plate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="factory_key",
            new_name="factory_year",
        ),
    ]
