# Generated by Django 5.0.7 on 2024-07-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_rename_factory_key_car_factory_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cars_count", models.IntegerField()),
                ("cars_value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
